### ISSUE TITLE
Dilithium 3 doesn't work in QEMU

### ISSUE THREAD

**Issue by paulsonmathew21** [mupq/pqm3#15]
Attempt to perform the available tests on Dilithium3 has been failed in the QEMU (version 4.2.1) environment. The emulator gets stuck, as if its in an endless loop, when selecting any of the test options available and required.

**Comment by mkannwischer** [comment]
Sorry for the delay! 
I'm assuming this issue occurs for the lm3s platform. 
The lm3s6965evb has 64 KiB. According to the benchmarks on the nucleo-f207zg, dilithium3 needs 80 KiB of stacks (plus keys, signature). So this will never work. 

This implementation should be automatically skipped, but somehow the memory consumption is reported wrongly in https://github.com/mupq/pqm3/blob/master/skiplist.py. 

You can use the mps2-an385 qemu platform instead which has much more RAM. You will need to update your qemu to at least 5.2 though. 

We are currently working on a Dilithium implementation using less RAM. If you are interested, please drop me an e-mail and I will update you when it is available. 

Cheers, 
Matthias
